(function(){
  const apiBase=String(window.ACE_CONFIG?.apiBase||'').replace(/\/$/,'');
  const recognition=Array.from({length:13},(_,index)=>`assets/recognition-${String(index+1).padStart(2,'0')}.png`);
  const valentines=Array.from({length:15},(_,index)=>`assets/black-valentines-${String(index+1).padStart(2,'0')}.png`);
  const christmas=Array.from({length:9},(_,index)=>`assets/christmas-${String(index+1).padStart(2,'0')}.png`);
  const jobs=[
    {id:'sales-representative',title:'Sales Representative',department:'Sales',category:'sales',employmentType:'Full-time',location:'Santa Rosa, Laguna',priority:'urgent',summary:'Join our dynamic team and help ACE expand its business and connect with clients worldwide.',responsibilities:['Identify and reach out to potential customers','Communicate with clients through calls, email, and meetings','Present services and explain their business value','Handle objections, negotiate terms, and close sales','Maintain customer relationships and provide follow-up support'],qualifications:['Strong communication and persuasion skills','Customer service orientation','Effective negotiation skills','Good time management','Resilience and adaptability']},
    {id:'customer-services',title:'Customer Services',department:'Customer Experience',category:'operations',employmentType:'Full-time',location:'Santa Rosa, Laguna',priority:'urgent',summary:'Support customers by answering questions, resolving concerns, and creating a positive experience.',responsibilities:['Handle customer inquiries by phone, email, and chat','Resolve customer concerns and provide clear solutions','Document interactions and escalate complex issues'],qualifications:['Clear and professional communication','Problem-solving ability','Patience and empathy','Attention to detail']},
    {id:'graphic-designer',title:'Graphic Designer',department:'Creative',category:'tech',employmentType:'Full-time',location:'Santa Rosa, Laguna',priority:'active',summary:'Bring fresh ideas and visually compelling designs to life as part of the ACE creative team.',responsibilities:['Create digital and print marketing materials','Develop on-brand graphics for web and social media','Collaborate with marketing and internal teams'],qualifications:['Strong visual design portfolio','Proficiency with modern design tools','A keen eye for detail']},
    {id:'hr-officer',title:'HR Officer',department:'Human Resources',category:'operations',employmentType:'Full-time',location:'Santa Rosa, Laguna',priority:'active',summary:'Support smooth workforce operations, employee relations, policy implementation, and a positive workplace environment.',responsibilities:['Support recruitment, hiring, and onboarding','Handle employee relations and workplace concerns','Maintain employee records and HR documentation'],qualifications:['Strong communication and organization','Knowledge of Philippine labor practices','Confidentiality and professional ethics']},
    {id:'software-developer',title:'Software Developer',department:'Technology',category:'tech',employmentType:'Full-time',location:'Hybrid',priority:'active',summary:'Design, develop, and maintain high-quality software solutions while collaborating with cross-functional teams.',responsibilities:['Build and maintain reliable applications','Translate business requirements into technical solutions','Review, test, and improve code quality'],qualifications:['Software development experience','Strong problem-solving skills','Experience with version control and APIs']},
    {id:'marketing-manager',title:'Marketing Manager',department:'Marketing',category:'sales',employmentType:'Full-time',location:'Santa Rosa, Laguna',priority:'active',summary:'Develop and oversee marketing strategies that build awareness, generate leads, and support business growth.',responsibilities:['Develop marketing strategies and campaign plans','Manage brand consistency and content','Track campaign performance and improve results'],qualifications:['Marketing strategy experience','Digital marketing knowledge','Strong analytical and creative thinking']},
    {id:'data-entry',title:'Data Entry',department:'Operations',category:'operations',employmentType:'Full-time',location:'Santa Rosa, Laguna',priority:'open',summary:'Enter, update, verify, and organize business data accurately across digital systems and databases.',responsibilities:['Enter and update data','Check records for errors','Maintain organized digital files'],qualifications:['Fast and accurate typing','Strong attention to detail','Basic computer and spreadsheet knowledge']},
    {id:'full-time-marketing-manager',title:'Full-Time Marketing Manager',department:'Marketing',category:'sales',employmentType:'Full-time',location:'Paseo de Sta. Rosa',priority:'open',summary:'Lead multi-channel marketing strategy, content, campaigns, performance analysis, and budget planning for ACE.',responsibilities:['Develop marketing plans','Manage digital and paid campaigns','Track KPIs, budgets, and return on investment'],qualifications:["Bachelor's degree in a related field",'Three to five years of marketing experience','Strong written, analytical, and creative skills']},
    {id:'full-stack-developer',title:'Full-Stack Developer',department:'Technology',category:'tech',employmentType:'Full-time',location:'Hybrid',priority:'open',summary:'Build and maintain a SaaS platform across web, iOS, and Android using Laravel, Vue.js, Flutter, and Node.js.',responsibilities:['Develop SaaS applications','Build cross-platform interfaces','Maintain CI/CD and cloud deployments'],qualifications:['Laravel and Vue.js experience','Flutter experience','Node.js and REST API experience']},
    {id:'sales-development-manager',title:'Sales Development Manager',department:'Sales',category:'sales',employmentType:'Full-time',location:'Paseo Outlet, Sta. Rosa',priority:'open',summary:'Drive lead generation, manage sales operations, and develop strategies to acquire new BPO clients.',responsibilities:['Develop lead generation strategies','Manage the sales funnel and CRM','Monitor performance'],qualifications:['Three or more years of B2B sales experience','Experience with outsourcing sales','Strong leadership and communication']}
  ];
  const defaults={
    team:[
      {id:'kristine-p',name:'Kristine P.',role:'Trainer',quote:'We don’t just train for the job. We train for growth.',image:'assets/team-kristine.png'},
      {id:'ash-pampuan',name:'Ash Pampuan',role:'Team Leader',quote:'Every team member should feel valued, supported and heard.',image:'assets/team-ash.png'},
      {id:'rose-esc',name:'Rose Esc',role:'Web Developer',quote:'Innovation helps us improve operations and client satisfaction.',image:'assets/team-rose.png'},
      {id:'byron-tabbada',name:'Byron Tabbada',role:'Human Resources',quote:'We create a workplace where people feel respected and motivated to grow.',image:'assets/team-byron.png'}
    ],
    testimonials:[
      {id:'jenny-m',name:'Jenny M.',company:'Be There Solutions',quote:'We could not be happier with our team. They are loyal, hardworking and dedicated. ACE helped us lower costs while improving our sales growth.',logo:'assets/be-there-solutions.png',rating:5},
      {id:'adam-j',name:'Adam J.',company:'Figshelf',quote:'ACE helped us put a plan in place to build and scale as our platform requires more manpower. We are excited about the journey and the outcome ahead.',logo:'assets/figshelf.png',rating:5},
      {id:'shai-a',name:'Shai A.',company:'Green Marketing',quote:'From day one, ACE was professional and created a plan to recruit, onboard, train and grow my sales team. The results have been excellent.',logo:'assets/green-marketing.png',rating:5}
    ],
    blogs:[
      {id:'dinner-night-out',title:'Dinner Night Out: Strengthening Bonds, Boosting Morale',category:'Team culture',author:'wpsuperadmin',date:'Jun 29, 2025',excerpt:'A meaningful evening to unwind, connect, and recharge as one team.',body:'In every successful team, connection and communication are just as important as performance and productivity. We recently took a well-deserved break from our busy routines to enjoy a Dinner Night Out, a simple yet meaningful way to unwind, connect, and recharge as one team.\n\nThe evening was filled with laughter, great conversations, and even greater food. It was an opportunity to strengthen our bonds outside the usual work environment.\n\nMoments like these remind us that building a strong team goes beyond the workplace. It is about fostering genuine relationships, boosting morale, and creating a culture where everyone feels seen, heard, and motivated.',cover:'assets/dinner-night-out.png',images:['assets/dinner-night-out.png']},
      {id:'recognizing-excellence',title:'Recognizing Excellence: Personal Goals and Top Performers',category:'Recognition',author:'wpsuperadmin',date:'Jun 29, 2025',excerpt:'Celebrating the people whose dedication, progress, and results inspire the whole team.',body:'At our company, we believe in celebrating growth, dedication, and results. We proudly recognize team members who go above and beyond through our Personal Goal Incentives and Top Performer awards.\n\nEach milestone represents a story of perseverance, dedication, and growth. Every effort counts, and every achievement helps move the entire team forward.\n\nCongratulations to all our top performers. Your excellence continues to inspire others to aim higher.',cover:'assets/recognition-01.png',images:recognition},
      {id:'ace-black-valentines',title:'ACE Black Valentine’s',category:'Celebration',author:'wpsuperadmin',date:'Jun 27, 2025',excerpt:'A day of appreciation, fun, and connection across the ACE team.',body:'Valentine’s Day is not just about romance. It is about celebrating all forms of love, including the appreciation and camaraderie we share in the workplace.\n\nOur Black Valentine’s theme represented strong and unwavering love for our families, our clients, and the company.',cover:'assets/black-valentines-01.png',images:valentines},
      {id:'christmas-celebration',title:'Highlights from Our Christmas Celebration',category:'Celebration',author:'wpsuperadmin',date:'Jun 27, 2025',excerpt:'Thoughtful giveaways, shared gratitude, and a joyful celebration across departments.',body:'The holiday season is all about giving, and this Christmas our company made it extra special with thoughtful giveaways that brought smiles to everyone’s faces.\n\nEach item was a token of appreciation for the hard work and dedication of our team. Moments like these remind us that the true gift of the season is the connection we build together.',cover:'assets/christmas-01.png',images:christmas}
    ],
    jobs
  };
  const clone=value=>JSON.parse(JSON.stringify(value));
  const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  let csrfToken='';
  const request=async(path,options={})=>{
    if(!apiBase)throw Object.assign(new Error('The secure backend has not been connected yet.'),{code:'NOT_CONFIGURED'});
    const method=options.method||'GET',headers={Accept:'application/json',...(options.headers||{})};
    if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';
    if(!['GET','HEAD','OPTIONS'].includes(method)&&csrfToken)headers['X-CSRF-Token']=csrfToken;
    const response=await fetch(`${apiBase}${path}`,{...options,method,headers,credentials:'include'});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw Object.assign(new Error(data.error||'The server request failed.'),{status:response.status});
    if(data.csrfToken)csrfToken=data.csrfToken;
    return data;
  };
  window.ACECMS={
    defaults:clone(defaults),uid,apiBase,isConfigured:Boolean(apiBase),
    async getContent(){try{return clone(await request('/content'))}catch(error){console.warn('Using bundled website content:',error.message);return clone(defaults)}},
    async saveContent(content){return request('/content',{method:'PUT',body:JSON.stringify(clone(content))})},
    async resetContent(){return request('/content',{method:'PUT',body:JSON.stringify(clone(defaults))})},
    async login(email,password){return request('/auth/login',{method:'POST',body:JSON.stringify({email,password})})},
    async getSession(){try{return await request('/auth/session')}catch(error){if(error.status===401||error.code==='NOT_CONFIGURED')return null;throw error}},
    async logout(){try{return await request('/auth/logout',{method:'POST'})}finally{csrfToken=''}}
  };
})();
